import React, { useState, useMemo } from 'react';
import { PieChart, Pie, Cell, ResponsiveContainer, Tooltip as RechartsTooltip, Legend } from 'recharts';
import { TrendingUp, TrendingDown, PieChart as PieIcon, Activity, Calendar, Download, CheckCircle2, List, Loader2 } from 'lucide-react';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export default function Reports({ monthlyData, owners, categories, savingsGoals }) {
  const availableMonths = Object.keys(monthlyData).sort().reverse();
  const [selectedMonth, setSelectedMonth] = useState(availableMonths[0] || new Date().toISOString().slice(0, 7));
  const [isGeneratingPdf, setIsGeneratingPdf] = useState(false);

  // --- MATH ENGINE ---
  const reportData = useMemo(() => {
    const data = monthlyData[selectedMonth] || { bills: [], incomes: {} };
    const bills = data.bills || [];
    const incomes = data.incomes || {};

    // 1. Calculate Total Income
    let totalIncome = 0;
    owners.forEach(owner => {
      const p1 = parseFloat(incomes[`${owner}_p1`] || 0);
      const p2 = parseFloat(incomes[`${owner}_p2`] || 0);
      const extra = parseFloat(incomes[`${owner}_extra`] || 0);
      totalIncome += p1 + p2 + extra;
    });

    // 2. Expenses & Lists
    let totalExpenses = 0;
    const categoryBreakdown = {};
    let fixedCosts = 0;
    let flexibleCosts = 0;
    
    const needsItems = [];
    const wantsItems = [];

    bills.forEach(bill => {
      totalExpenses += bill.amount;
      const cat = bill.category || 'other';
      categoryBreakdown[cat] = (categoryBreakdown[cat] || 0) + bill.amount;

      if (['housing', 'utilities', 'debt', 'health', 'transport'].includes(cat)) {
        fixedCosts += bill.amount;
        needsItems.push(bill);
      } else {
        flexibleCosts += bill.amount;
        wantsItems.push(bill);
      }
    });

    needsItems.sort((a, b) => b.amount - a.amount);
    wantsItems.sort((a, b) => b.amount - a.amount);

    const netCashFlow = totalIncome - totalExpenses;
    const savingsRate = totalIncome > 0 ? ((netCashFlow / totalIncome) * 100).toFixed(1) : 0;
    const totalLiquidSavings = savingsGoals.reduce((sum, g) => sum + g.totalPaid, 0);
    const monthsOfRunway = totalExpenses > 0 ? (totalLiquidSavings / totalExpenses).toFixed(1) : 0;

    return { totalIncome, totalExpenses, netCashFlow, savingsRate, categoryBreakdown, fixedCosts, flexibleCosts, totalLiquidSavings, monthsOfRunway, needsItems, wantsItems };
  }, [selectedMonth, monthlyData, owners, savingsGoals]);

  const pieData = Object.entries(reportData.categoryBreakdown).map(([key, value]) => ({
    name: categories[key]?.label || key,
    value,
    color: categories[key]?.color || '#94a3b8'
  })).sort((a, b) => b.value - a.value);

  const monthLabel = new Date(selectedMonth + '-01').toLocaleString('default', { month: 'long', year: 'numeric' });

  // --- PROFESSIONAL PDF GENERATOR ---
  const handleDownloadPDF = () => {
    setIsGeneratingPdf(true);
    const doc = new jsPDF();

    // 1. BRANDING & HEADER
    doc.setFontSize(22);
    doc.setTextColor(40, 40, 40);
    doc.text('Monthly Financial Report', 14, 20);
    
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text(`Generated by OmegaBudget | ${monthLabel}`, 14, 26);

    // 2. EXECUTIVE SUMMARY BOX
    doc.setFillColor(245, 247, 250); // Light gray background
    doc.roundedRect(14, 35, 180, 35, 3, 3, 'F');

    // Net Cash Flow
    doc.setFontSize(9);
    doc.setTextColor(100);
    doc.text('NET CASH FLOW', 20, 45);
    doc.setFontSize(16);
    doc.setTextColor(reportData.netCashFlow >= 0 ? 34 : 239, reportData.netCashFlow >= 0 ? 197 : 68, reportData.netCashFlow >= 0 ? 94 : 68); // Green or Red
    doc.text(`$${reportData.netCashFlow.toFixed(2)}`, 20, 53);
    doc.setFontSize(10);
    doc.setTextColor(40);
    doc.text(`${reportData.savingsRate}% Savings Rate`, 20, 60);

    // Income
    doc.setFontSize(9);
    doc.setTextColor(100);
    doc.text('TOTAL INCOME', 80, 45);
    doc.setFontSize(14);
    doc.setTextColor(40);
    doc.text(`$${reportData.totalIncome.toFixed(0)}`, 80, 53);

    // Expenses
    doc.setFontSize(9);
    doc.setTextColor(100);
    doc.text('TOTAL SPENT', 140, 45);
    doc.setFontSize(14);
    doc.setTextColor(40);
    doc.text(`$${reportData.totalExpenses.toFixed(0)}`, 140, 53);

    // 3. RUNWAY METRIC
    doc.setFontSize(11);
    doc.text('Financial Health Check', 14, 85);
    doc.setFontSize(10);
    doc.setTextColor(100);
    doc.text(`You have ${reportData.monthsOfRunway} months of emergency runway based on current savings ($${reportData.totalLiquidSavings}) and burn rate.`, 14, 91);

    // 4. ITEMIZED TABLES
    // Needs Table
    doc.setFontSize(11);
    doc.setTextColor(40);
    doc.text('Needs (Fixed Expenses)', 14, 105);
    
    autoTable(doc, {
      startY: 108,
      head: [['Bill Name', 'Category', 'Amount']],
      body: reportData.needsItems.map(item => [
        item.name, 
        categories[item.category]?.label || 'Other', 
        `$${item.amount.toFixed(2)}`
      ]),
      theme: 'grid',
      headStyles: { fillColor: [239, 68, 68] }, // Red header for Needs
      styles: { fontSize: 9 },
    });

    // Wants Table (Starts after Needs table)
    const finalY = doc.lastAutoTable.finalY + 15;
    
    doc.text('Wants (Flexible Spending)', 14, finalY);
    
    autoTable(doc, {
      startY: finalY + 3,
      head: [['Bill Name', 'Category', 'Amount']],
      body: reportData.wantsItems.map(item => [
        item.name, 
        categories[item.category]?.label || 'Other', 
        `$${item.amount.toFixed(2)}`
      ]),
      theme: 'grid',
      headStyles: { fillColor: [59, 130, 246] }, // Blue header for Wants
      styles: { fontSize: 9 },
    });

    doc.save(`OmegaBudget_${selectedMonth}.pdf`);
    setIsGeneratingPdf(false);
  };

  return (
    <div className="animate-fade-in" style={{ paddingBottom: 60 }}>
      {/* HEADER & CONTROLS */}
      <header className="page-header" style={{ marginBottom: 20 }}>
        <div>
          <h1 style={{ fontSize: '1.5rem', display: 'flex', alignItems: 'center', gap: 10 }}>
            <Activity size={28} color="var(--accent)" /> Financial Reports
          </h1>
          <p className="subtitle">Executive summary for {monthLabel}</p>
        </div>
        
        <div style={{ display: 'flex', gap: 10 }}>
          <div className="select-wrapper-small">
            <Calendar size={16} className="icon" />
            <select 
              value={selectedMonth} 
              onChange={(e) => setSelectedMonth(e.target.value)}
              style={{ fontSize: '1rem', padding: '8px 12px 8px 32px' }}
            >
              {availableMonths.length > 0 ? availableMonths.map(m => (
                <option key={m} value={m}>{m}</option>
              )) : <option value={selectedMonth}>{selectedMonth}</option>}
            </select>
          </div>

          <button 
            className="btn-primary" 
            onClick={handleDownloadPDF} 
            disabled={isGeneratingPdf}
            style={{ fontSize: '0.9rem' }}
          >
            {isGeneratingPdf ? <Loader2 className="spin" size={16}/> : <Download size={16} />}
            {isGeneratingPdf ? ' Generating...' : ' Download PDF Report'}
          </button>
        </div>
      </header>

      {/* DASHBOARD VISUALS (Visible on Screen) */}
      
      {/* 1. THE CFO "1-PAGER" HERO CARD */}
      <div className="report-hero-card">
        <div className="hero-metric">
          <span className="hero-label">Net Cash Flow</span>
          <span className={`hero-value ${reportData.netCashFlow >= 0 ? 'pos' : 'neg'}`}>
            {reportData.netCashFlow >= 0 ? '+' : ''}${reportData.netCashFlow.toFixed(2)}
          </span>
          <span className="hero-sub">{reportData.savingsRate}% Savings Rate</span>
        </div>
        
        <div className="hero-divider"></div>

        <div className="hero-metric">
          <span className="hero-label">Total Income</span>
          <span className="hero-value text-default">${reportData.totalIncome.toFixed(0)}</span>
          <span className="hero-sub" style={{color: 'var(--green)'}}><TrendingUp size={12}/> Inflow</span>
        </div>

        <div className="hero-metric">
          <span className="hero-label">Total Expenses</span>
          <span className="hero-value text-default">${reportData.totalExpenses.toFixed(0)}</span>
          <span className="hero-sub" style={{color: 'var(--red)'}}><TrendingDown size={12}/> Outflow</span>
        </div>
      </div>

      <div className="reports-grid">
        
        {/* 2. LIFESTYLE AUDIT (NEEDS VS WANTS) */}
        <div className="card report-card">
          <h3><PieIcon size={18}/> Lifestyle Audit</h3>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', height: 220 }}>
            <ResponsiveContainer width="100%" height="100%">
              <PieChart>
                <Pie 
                  data={[
                    { name: 'Needs (Fixed)', value: reportData.fixedCosts, color: '#ef4444' },
                    { name: 'Wants (Flexible)', value: reportData.flexibleCosts, color: '#3b82f6' },
                    { name: 'Unspent (Saved)', value: Math.max(0, reportData.netCashFlow), color: '#22c55e' }
                  ]} 
                  cx="50%" cy="50%" 
                  innerRadius={60} 
                  outerRadius={80} 
                  paddingAngle={5} 
                  dataKey="value"
                >
                  <Cell fill="#ef4444"/>
                  <Cell fill="#3b82f6"/>
                  <Cell fill="#22c55e"/>
                </Pie>
                <RechartsTooltip 
                  contentStyle={{ backgroundColor: 'var(--card)', borderRadius: 8, border: '1px solid var(--border)' }}
                  itemStyle={{ color: 'var(--text)' }}
                  formatter={(value) => `$${value.toFixed(0)}`}
                />
                <Legend verticalAlign="bottom" height={36}/>
              </PieChart>
            </ResponsiveContainer>
          </div>
          <p style={{ textAlign: 'center', fontSize: '0.9rem', color: 'var(--text-dim)', marginTop: 0 }}>
            You spent <b>${reportData.flexibleCosts.toFixed(0)}</b> on flexible lifestyle choices this month.
          </p>
        </div>

        {/* 3. CATEGORY BREAKDOWN */}
        <div className="card report-card">
          <h3>Top Expense Categories</h3>
          <div className="category-rank-list">
            {pieData.slice(0, 5).map((cat, idx) => (
              <div key={idx} className="rank-item">
                <div className="rank-bar-bg">
                  <div 
                    className="rank-bar-fill" 
                    style={{ 
                      width: `${(cat.value / reportData.totalExpenses) * 100}%`, 
                      backgroundColor: cat.color 
                    }}
                  ></div>
                </div>
                <div className="rank-info">
                  <span className="rank-name">{cat.name}</span>
                  <span className="rank-val">${cat.value.toFixed(0)}</span>
                </div>
              </div>
            ))}
          </div>
        </div>

        {/* 4. FREEDOM FORECAST (RUNWAY) */}
        <div className="card report-card full-width" style={{ background: 'linear-gradient(135deg, var(--card) 0%, rgba(34, 197, 94, 0.05) 100%)' }}>
          <h3><CheckCircle2 size={18} color="var(--green)"/> Freedom Forecast</h3>
          <div style={{ display: 'flex', justifyContent: 'space-around', alignItems: 'center', flexWrap: 'wrap', gap: 20 }}>
            <div className="forecast-stat">
              <span className="f-label">Total Liquid Savings</span>
              <span className="f-val">${reportData.totalLiquidSavings.toFixed(0)}</span>
            </div>
            <div className="forecast-stat">
              <span className="f-label">Avg Monthly Burn</span>
              <span className="f-val" style={{color: 'var(--red)'}}>-${reportData.totalExpenses.toFixed(0)}</span>
            </div>
            <div className="forecast-stat highlight">
              <span className="f-label">Safety Runway</span>
              <span className="f-val text-accent">{reportData.monthsOfRunway} Months</span>
              <span className="f-sub">If income stopped today</span>
            </div>
          </div>
        </div>

        {/* 5. ITEMIZED BREAKDOWN (TABLE) */}
        <div className="card report-card full-width">
          <h3><List size={18}/> Itemized Breakdown</h3>
          <div className="split-list-container">
            
            {/* NEEDS COLUMN */}
            <div className="split-col">
              <h4 style={{ color: '#ef4444', borderBottom: '2px solid #ef4444' }}>Needs (Fixed)</h4>
              <div className="detail-list">
                {reportData.needsItems.length > 0 ? reportData.needsItems.map((item, i) => (
                  <div key={i} className="detail-row">
                    <span className="d-name">{item.name}</span>
                    <span className="d-val">${item.amount.toFixed(0)}</span>
                  </div>
                )) : <div className="empty-msg">No fixed bills found.</div>}
              </div>
            </div>

            {/* WANTS COLUMN */}
            <div className="split-col">
              <h4 style={{ color: '#3b82f6', borderBottom: '2px solid #3b82f6' }}>Wants (Flexible)</h4>
              <div className="detail-list">
                {reportData.wantsItems.length > 0 ? reportData.wantsItems.map((item, i) => (
                  <div key={i} className="detail-row">
                    <span className="d-name">{item.name}</span>
                    <span className="d-val">${item.amount.toFixed(0)}</span>
                  </div>
                )) : <div className="empty-msg">No flexible spending found.</div>}
              </div>
            </div>

          </div>
        </div>

      </div>
    </div>
  );
}